export const SELECT_NOTE = 'SELECT_NOTE';
export const DESELECT_NOTE = 'DESELECT_NOTE';
export const UPDATE_SELECTED_CHORD_NAME = 'UPDATE_SELECTED_CHORD_NAME';
export const UPDATE_SELECTED_KEY_NUMBER = 'UPDATE_SELECTED_KEY_NUMBER';
export const UPDATE_SELECTED_SCALE_NAME = 'UPDATE_SELECTED_SCALE_NAME';
export const UPDATE_SELECTED_SELECTION_TYPE = 'UPDATE_SELECTED_SELECTION_TYPE';
export const UPDATE_TUNER_NUMBER = 'UPDATE_TUNER_NUMBER';
