export const SELECT_NOTE = 'SELECT_NOTE';
export const DESELECT_NOTE = 'DESELECT_NOTE';
export const UPDATE_SELECTED_KEY = 'UPDATE_SELECTED_KEY';
export const UPDATE_TUNER_NUMBER = 'UPDATE_TUNER_NUMBER';
